export const packages = [
  {
    category: 'default-packages',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description:
          'Essential audio setup for church events and intimate gatherings.',
        price: '7,000',
        features: [
          'Clear, warm sound for vocals',
          'Church-appropriate lighting',
          'Professional audio mixing',
          'Respectful minimal setup',
          'Experienced church technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Microphone: 2× Wireless microphones (MIPRO 311B)',
          'Microphone: 1× Wired microphone (Sennheiser E935)',
          'Lights: 4× PAR RGB backlights (Kosmo/Aerolites)',
          'Lights: 1× DMX 512 Controller',
          'Lights: 4× Amber front lights (Kosmo/Aerolites)',
          'Lights: 2× T-bar stands (holds PAR lights)',
          'Others: 2× Speaker stands, cables, extensions',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/church-anniversary/church-anniversary-1.jpg',
        ],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete full-band setup for school events with all drums, amplifiers, and professional audio support.',
        price: '25,000',
        features: [
          'Full band audio and amplification',
          'Complete drum miking setup',
          'Dynamic stage lighting',
          'Professional mixing and monitoring',
          'Expert crew for band performances',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Audio System: 2× Subwoofers (QSC KLA181)',
          'Audio System: 4× Monitor speakers (QSC K12 & Yamaha DXR10)',
          'Audio System: 1× Digital stage box (Allen & Heath AR2412)',
          'Microphone: 2× Wireless microphones (MIPRO 311B)',
          'Microphone: 2× Wired microphones (Sennheiser E935)',
          'Drums: Drumset (Pearl Export)',
          'Drums: Cymbals (Sabian HMX & AAX)',
          'Drums: Kick pedal (Iron Cobra 600)',
          'Drums: Kick mic (Shure Beta 52A)',
          'Drums: Snare mic (Shure SM57)',
          'Drums: 2× Tom mics (Shure PGA 56)',
          'Drums: 1× Overhead mic (Shure PGA 81)',
          'Amplifiers: 2× Guitar amplifiers (Laney LX120R Twin)',
          'Amplifiers: Bass amplifier (GK MB115)',
          'Amplifiers: 2× Guitar mics (Shure SM56)',
          'Lights: 8× PAR RGB backlights (Kosmo/Aerolites)',
          'Lights: 1× Light controller (MiniPearl 1024)',
          'Lights: 4× Amber front lights (4×50W LED PAR)',
          'Lights: 4× T-bar stands (holds PAR lights)',
          'Others: 2× Speaker stands (height adjustable)',
          'Others: XLR cables (enough for event)',
          'Others: 2× Cable ramps (solid quality)',
          'Others: Extension cables (high quality)',
          'Others: 3.5mm AUX cable (play your music)',
          'Others: 3× Mic stands (with press to adjust)',
          'Others: 1× Lyric stand (add upon request)',
          'Others: 1× Fog machine (Titanium Audio)',
          'Crew & Transport: 5× Tech crew (experts from Legato)',
          'Crew & Transport: Transport service (Mitsubishi L300)',
        ],
        sampleImages: [
          '/packages-sample-images/school-full-band/school-full-band-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete full-band setup for school events with all drums, amplifiers, and professional audio support.',
        price: '25,000',
        features: [
          'Full band audio and amplification',
          'Complete drum miking setup',
          'Dynamic stage lighting',
          'Professional mixing and monitoring',
          'Expert crew for band performances',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Audio System: 2× Subwoofers (QSC KLA181)',
          'Audio System: 4× Monitor speakers (QSC K12 & Yamaha DXR10)',
          'Audio System: 1× Digital stage box (Allen & Heath AR2412)',
          'Microphone: 2× Wireless microphones (MIPRO 311B)',
          'Microphone: 2× Wired microphones (Sennheiser E935)',
          'Drums: Drumset (Pearl Export)',
          'Drums: Cymbals (Sabian HMX & AAX)',
          'Drums: Kick pedal (Iron Cobra 600)',
          'Drums: Kick mic (Shure Beta 52A)',
          'Drums: Snare mic (Shure SM57)',
          'Drums: 2× Tom mics (Shure PGA 56)',
          'Drums: 1× Overhead mic (Shure PGA 81)',
          'Amplifiers: 2× Guitar amplifiers (Laney LX120R Twin)',
          'Amplifiers: Bass amplifier (GK MB115)',
          'Amplifiers: 2× Guitar mics (Shure SM56)',
          'Lights: 8× PAR RGB backlights (Kosmo/Aerolites)',
          'Lights: 1× Light controller (MiniPearl 1024)',
          'Lights: 4× Amber front lights (4×50W LED PAR)',
          'Lights: 4× T-bar stands (holds PAR lights)',
          'Others: 2× Speaker stands (height adjustable)',
          'Others: XLR cables (enough for event)',
          'Others: 2× Cable ramps (solid quality)',
          'Others: Extension cables (high quality)',
          'Others: 3.5mm AUX cable (play your music)',
          'Others: 3× Mic stands (with press to adjust)',
          'Others: 1× Lyric stand (add upon request)',
          'Others: 1× Fog machine (Titanium Audio)',
          'Crew & Transport: 5× Tech crew (experts from Legato)',
          'Crew & Transport: Transport service (Mitsubishi L300)',
        ],
        sampleImages: [
          '/packages-sample-images/school-full-band/school-full-band-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'school-full-band',
    packages: [
      {
        id: 1,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete full-band setup for school events with all drums, amplifiers, and professional audio support.',
        price: '25,000',
        features: [
          'Full band audio and amplification',
          'Complete drum miking setup',
          'Dynamic stage lighting',
          'Professional mixing and monitoring',
          'Expert crew for band performances',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Audio System: 2× Subwoofers (QSC KLA181)',
          'Audio System: 4× Monitor speakers (QSC K12 & Yamaha DXR10)',
          'Audio System: 1× Digital stage box (Allen & Heath AR2412)',
          'Microphone: 2× Wireless microphones (MIPRO 311B)',
          'Microphone: 2× Wired microphones (Sennheiser E935)',
          'Drums: Drumset (Pearl Export)',
          'Drums: Cymbals (Sabian HMX & AAX)',
          'Drums: Kick pedal (Iron Cobra 600)',
          'Drums: Kick mic (Shure Beta 52A)',
          'Drums: Snare mic (Shure SM57)',
          'Drums: 2× Tom mics (Shure PGA 56)',
          'Drums: 1× Overhead mic (Shure PGA 81)',
          'Amplifiers: 2× Guitar amplifiers (Laney LX120R Twin)',
          'Amplifiers: Bass amplifier (GK MB115)',
          'Amplifiers: 2× Guitar mics (Shure SM56)',
          'Lights: 8× PAR RGB backlights (Kosmo/Aerolites)',
          'Lights: 1× Light controller (MiniPearl 1024)',
          'Lights: 4× Amber front lights (4×50W LED PAR)',
          'Lights: 4× T-bar stands (holds PAR lights)',
          'Others: 2× Speaker stands (height adjustable)',
          'Others: XLR cables (enough for event)',
          'Others: 2× Cable ramps (solid quality)',
          'Others: Extension cables (high quality)',
          'Others: 3.5mm AUX cable (play your music)',
          'Others: 3× Mic stands (with press to adjust)',
          'Others: 1× Lyric stand (add upon request)',
          'Others: 1× Fog machine (Titanium Audio)',
          'Crew & Transport: 5× Tech crew (experts from Legato)',
          'Crew & Transport: Transport service (Mitsubishi L300)',
        ],
        sampleImages: [
          '/packages-sample-images/school-full-band/school-full-band-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium full-band setup featuring moving lights for maximum visual impact and performance.',
        price: '30,000',
        features: [
          'Concert-level audio and lighting',
          'Full band with complete drum setup',
          'Moving lights for dynamic effects',
          'Large venue and outdoor capability',
          'Premium technical crew and support',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Audio System: 2× Subwoofers (QSC KLA181)',
          'Audio System: 4× Monitor speakers (QSC K12 & Yamaha DXR10)',
          'Audio System: 1× Digital stage box (Allen & Heath AR2412)',
          'Microphone: 2× Wireless microphones (MIPRO 311B)',
          'Microphone: 2× Wired microphones (Sennheiser E935)',
          'Drums: Drumset (Pearl Export)',
          'Drums: Cymbals (Sabian HMX & AAX)',
          'Drums: Kick pedal (Iron Cobra 600)',
          'Drums: Kick mic (Shure Beta 52A)',
          'Drums: Snare mic (Shure SM57)',
          'Drums: 2× Tom mics (Shure PGA 56)',
          'Drums: 1× Overhead mic (Shure PGA 81)',
          'Amplifiers: 2× Guitar amplifiers (Laney LX120R Twin)',
          'Amplifiers: Bass amplifier (GK MB115)',
          'Amplifiers: 2× Guitar mics (Shure SM56)',
          'Lights: 8× PAR RGB backlights (Kosmo/Aerolites)',
          'Lights: 1× Light controller (MiniPearl 1024)',
          'Lights: 4× Amber front lights (4×50W LED PAR)',
          'Lights: 4× T-bar stands (holds PAR lights)',
          'Lights: 2× Moving headlights (Beam 295)',
          'Lights: 2× Moving wash (19×15W LED)',
          'Others: 2× Speaker stands (height adjustable)',
          'Others: XLR cables (enough for event)',
          'Others: 2× Cable ramps (solid quality)',
          'Others: Extension cables (high quality)',
          'Others: 3.5mm AUX cable (play your music)',
          'Others: 3× Mic stands (with press to adjust)',
          'Others: 1× Lyric stand (add upon request)',
          'Others: 1× Fog machine (Titanium Audio)',
          'Crew & Transport: 5× Tech crew (experts from Legato)',
          'Crew & Transport: Transport service (Mitsubishi L300)',
        ],
        sampleImages: [
          '/packages-sample-images/school-full-band/school-full-band-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'church-anniversary',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description:
          'Essential audio setup for church events and intimate gatherings.',
        price: '7,000',
        features: [
          'Clear, warm sound for vocals',
          'Church-appropriate lighting',
          'Professional audio mixing',
          'Respectful minimal setup',
          'Experienced church technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Microphone: 2× Wireless microphones (MIPRO 311B)',
          'Microphone: 1× Wired microphone (Sennheiser E935)',
          'Lights: 4× PAR RGB backlights (Kosmo/Aerolites)',
          'Lights: 1× DMX 512 Controller',
          'Lights: 4× Amber front lights (Kosmo/Aerolites)',
          'Lights: 2× T-bar stands (holds PAR lights)',
          'Others: 2× Speaker stands, cables, extensions',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/church-anniversary/church-anniversary-1.jpg',
        ],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description:
          'Enhanced setup with better sound projection for larger churches.',
        price: '10,000',
        features: [
          'Enhanced sound depth and clarity',
          'Better coverage for larger venues',
          'Improved audio quality for choirs',
          'Elegant visual presentation',
          'Professional crew support',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Audio System: 2× Subwoofers (QSC KW181)',
          'Microphone: 2× Wireless microphones (MIPRO 311B)',
          'Microphone: 1× Wired microphone (Sennheiser E935)',
          'Lights: 4× PAR RGB backlights, 1× DMX Controller',
          'Lights: 4× Amber front lights, 2× T-bar stands',
          'Others: 2× Speaker stands, cables, extensions',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description:
          'Premium setup for cathedral performances and special celebrations.',
        price: '12,000',
        features: [
          'Professional-grade sound system',
          'Full choir and musician support',
          'Enhanced lighting ambiance',
          'Better stage presence',
          'Expert technical crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Audio System: 2× Subwoofers (QSC KW181)',
          'Audio System: 2× Monitor speakers (QSC K12)',
          'Microphone: 2× Wireless microphones, 1× Wired microphone',
          'Lights: 4× PAR RGB backlights, 4× Amber front lights',
          'Lights: 1× DMX Controller, 2× T-bar stands',
          'Others: 2× Speaker stands, cables, extensions',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description:
          'Advanced setup for grand celebrations and major church events.',
        price: '15,000',
        features: [
          'Concert-level audio quality',
          'Enhanced stage lighting design',
          'Full band capability',
          'Large venue coverage',
          'Professional technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer, 2× Subwoofers',
          'Audio System: 2× Monitor speakers (QSC K12)',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 8× PAR RGB backlights, 8× Amber front lights',
          'Lights: 1× DMX Controller, 2× T-bar stands',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete band setup for major anniversary celebrations and special events.',
        price: '25,000',
        features: [
          'Full band audio and amplification',
          'Complete drum and instrument support',
          'Dynamic stage lighting',
          'Professional monitoring setup',
          'Expert crew for performances',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Drumset with full miking (kick, snare, toms, overhead)',
          'Amplifiers: 2× Guitar amps, 1× Bass amp with mics',
          'Lights: 8× PAR backlights, 4× Amber front lights',
          'Lights: 1× Light controller, 4× T-bar stands',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/church-anniversary/church-anniversary-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium package with moving lights for maximum celebration impact.',
        price: '30,000',
        features: [
          'Concert-level audio system',
          'Full band with all instruments',
          'Moving lights for visual impact',
          'Large venue capability',
          'Premium technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp with mics',
          'Lights: 8× PAR backlights, 4× Amber front lights',
          'Lights: 2× Moving headlights (Beam 295)',
          'Lights: 2× Moving wash (19×15W LED)',
          'Lights: 1× Light controller, 4× T-bar stands',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/church-anniversary/church-anniversary-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'corporate-events',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description:
          'Professional audio setup for corporate presentations and meetings.',
        price: '7,000',
        features: [
          'Clear presentation audio',
          'Professional stage setup',
          'Discrete lighting design',
          'Corporate-appropriate aesthetics',
          'Experienced technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers (RCF ART 745A MK4)',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Microphone: 2× Wireless microphones, 1× Wired microphone',
          'Lights: 4× PAR RGB backlights, 4× Amber front lights',
          'Lights: 1× DMX Controller, 2× T-bar stands',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/corporate-events/corporate-events-1.jpg'],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description:
          'Enhanced setup with subwoofers for better audio projection.',
        price: '10,000',
        features: [
          'Improved sound coverage',
          'Professional audio quality',
          'Better venue coverage',
          'Corporate image enhancement',
          'Experienced crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer, 2× Subwoofers',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 4× PAR backlights, 4× Amber front lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description:
          'Premium setup for high-level corporate events and conferences.',
        price: '12,000',
        features: [
          'Professional-grade audio',
          'Enhanced stage presentation',
          'Multiple speaker support',
          'Professional lighting',
          'Expert technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors',
          'Audio System: 1× Digital mixer (Allen & Heath SQ5)',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 4× PAR backlights, 4× Amber front lights',
          'Lights: 1× DMX Controller, 2× T-bar stands',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description:
          'Advanced setup with enhanced lighting for large conferences.',
        price: '15,000',
        features: [
          'High-quality presentation audio',
          'Enhanced stage lighting',
          'Large venue support',
          'Professional presentation setup',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors',
          'Audio System: 1× Digital mixer',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 8× PAR backlights, 8× Amber front lights',
          'Lights: 1× DMX Controller, 2× T-bar stands',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete entertainment setup for premium corporate events.',
        price: '25,000',
        features: [
          'Full band audio support',
          'Dynamic stage lighting',
          'Professional monitoring',
          'Complete band equipment',
          'Expert technical crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber front lights',
          'Lights: 1× Light controller, 4× T-bar stands',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/corporate-events/corporate-events-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description: 'Premium package with moving lights for maximum impact.',
        price: '30,000',
        features: [
          'Concert-level setup',
          'Full band with all equipment',
          'Dynamic moving lights',
          'Large venue capability',
          'Premium technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber front lights',
          'Lights: 2× Moving headlights, 2× Moving wash',
          'Lights: 1× Light controller, 4× T-bar stands',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/corporate-events/corporate-events-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'cozy-cove-style',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description:
          'Intimate sound system perfect for cozy venues and close-knit gatherings.',
        price: '7,000',
        features: [
          'Warm intimate sound profile',
          'Ambient lighting setup',
          'Comfortable acoustic experience',
          'Minimal visual intrusion',
          'Professional audio support',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer',
          'Microphone: 2× Wireless microphones',
          'Lights: 4× PAR RGB backlights, 4× Amber lights',
          'Lights: 1× DMX Controller, 2× T-bar stands',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/cozy-cove-style/cozy-cove-style-1.jpg'],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description: 'Enhanced warmth with subwoofers for intimate venues.',
        price: '10,000',
        features: [
          'Premium warm acoustics',
          'Better sound projection',
          'Enhanced intimate feel',
          'Professional setup',
          'Experienced technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Professional intimate setup with monitor support.',
        price: '12,000',
        features: [
          'Premium sound quality',
          'Sophisticated ambient lighting',
          'Full performance support',
          'Elegant presentation',
          'Dedicated technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description: 'Advanced intimate setup with enhanced lighting design.',
        price: '15,000',
        features: [
          'Premium sound profile',
          'Sophisticated lighting design',
          'Full performance capability',
          'Elegant atmosphere',
          'Expert technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 8× PAR backlights, 8× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description: 'Premium band setup for upscale intimate venues.',
        price: '25,000',
        features: [
          'Full band audio support',
          'Dynamic stage lighting',
          'Professional monitoring',
          'Elegant performance setup',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 4× T-bars',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/cozy-cove-style/cozy-cove-style-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium package with moving lights for upscale performances.',
        price: '30,000',
        features: [
          'Concert-level intimate setup',
          'Full band with all equipment',
          'Moving lights for ambiance',
          'Premium presentation',
          'Expert technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 2× Moving headlights',
          'Lights: 2× Moving wash, 4× T-bars, 1× Controller',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/cozy-cove-style/cozy-cove-style-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'restobar-band-setup',
    packages: [
      {
        id: 1,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete professional band setup for restaurant and bar environments.',
        price: '25,000',
        features: [
          'Concert-quality band sound',
          'Full band with all equipment',
          'Professional monitoring',
          'Dynamic lighting effects',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp with mics',
          'Lights: 8× PAR backlights, 4× Amber lights, 4× T-bars',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/restobar-band-setup/restobar-band-setup-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium setup with moving lights for premium venue experiences.',
        price: '30,000',
        features: [
          'Exceptional band audio quality',
          'Full professional band setup',
          'Dynamic moving lights',
          'Premium venue presentation',
          'Top-tier technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp with mics',
          'Lights: 8× PAR backlights, 4× Amber lights, 2× Moving headlights',
          'Lights: 2× Moving wash, 4× T-bars, 1× Controller',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/restobar-band-setup/restobar-band-setup-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'gymnasium-events',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description:
          'Powerful audio for gymnasium events and sports competitions.',
        price: '7,000',
        features: [
          'Loud clear audio for large spaces',
          'Full gymnasium coverage',
          'Basic colorful lighting',
          'Event support',
          'Professional technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/gymnasium-events/gymnasium-events-1.jpg'],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description:
          'Enhanced system with subwoofers for large gymnasium venues.',
        price: '10,000',
        features: [
          'Powerful sound with great coverage',
          'Full gymnasium reach',
          'Dynamic lighting',
          'Large crowd support',
          'Professional crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Professional system with full gymnasium coverage.',
        price: '12,000',
        features: [
          'High-quality sound projection',
          'Full venue support',
          'Stage monitoring',
          'Large event capability',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description: 'Advanced setup with enhanced lighting for major events.',
        price: '15,000',
        features: [
          'Professional-grade sound',
          'Enhanced stage lighting',
          'Large venue capability',
          'Event management support',
          'Expert technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 8× PAR backlights, 8× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete entertainment system for major gymnasium events.',
        price: '25,000',
        features: [
          'Full band audio system',
          'Dynamic stage lighting',
          'Professional monitoring',
          'Large crowd entertainment',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 4× T-bars',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/gymnasium-events/gymnasium-events-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium system with moving lights for championship events.',
        price: '30,000',
        features: [
          'Concert-level audio',
          'Full band with equipment',
          'Dynamic moving lights',
          'Maximum visual impact',
          'Top technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 2× Moving headlights',
          'Lights: 2× Moving wash, 4× T-bars, 1× Controller',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/gymnasium-events/gymnasium-events-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'multi-track-studio-recording',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description:
          'Multi-track recording setup for studio recording sessions.',
        price: '7,000',
        features: [
          'Professional recording equipment',
          'Clean audio capture',
          'Basic mixing console',
          'Vocal and instrument recording',
          'Experienced sound engineer',
        ],
        equipment: [
          'Recording: 8-channel multi-track interface',
          'Mixing: Professional mixing console',
          'Microphone: 4× Studio microphones with stands',
          'Acoustic: Basic acoustic treatment',
          'Monitoring: Headphone monitoring system',
          'Others: Cables, connectors, extensions',
          'Crew: Sound engineer on-site',
        ],
        sampleImages: [
          '/event-types/multi-track-studio-recording/studio-recording-1.jpg',
        ],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description: 'Enhanced recording with better monitoring setup.',
        price: '10,000',
        features: [
          'Improved audio clarity',
          'Better monitoring capability',
          'Professional recording setup',
          'Mixing support',
          'Expert engineer',
        ],
        equipment: [
          'Recording: 12-channel multi-track interface',
          'Mixing: Professional mixing console',
          'Microphone: 6× Studio microphones',
          'Acoustic: Enhanced acoustic treatment',
          'Monitoring: Headphone + monitor speaker system',
          'Others: Cables, connectors, extensions',
          'Crew: Sound engineer on-site',
        ],
        addOns: [
          'Additional microphone + stand (+2,000)',
          'Vocal booth rental (+3,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Professional recording with full monitoring setup.',
        price: '12,000',
        features: [
          'High-quality recording',
          'Advanced mixing console',
          'Full acoustic treatment',
          'Professional monitoring',
          'Mixing support included',
        ],
        equipment: [
          'Recording: 16-channel multi-track interface',
          'Mixing: Advanced mixing console (Allen & Heath)',
          'Microphone: 8× Professional studio microphones',
          'Acoustic: Complete acoustic treatment',
          'Monitoring: Headphone + near-field monitor system',
          'Others: Cables, connectors, extensions',
          'Crew: Sound engineer and mixer on-site',
        ],
        addOns: [
          'Additional microphone (+2,000)',
          'Vocal booth rental (+3,000)',
        ],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description:
          'Premium recording setup for professional album production.',
        price: '15,000',
        features: [
          'Professional-grade recording',
          'Advanced mixing capabilities',
          'Full studio treatment',
          'Mixing and mastering support',
          'Expert technical team',
        ],
        equipment: [
          'Recording: 20-channel multi-track interface',
          'Mixing: Professional mixing console',
          'Microphone: 10× Studio microphones',
          'Acoustic: Complete professional treatment',
          'Monitoring: Complete monitoring system',
          'Mastering: Basic mastering tools',
          'Others: Cables, connectors, extensions',
          'Crew: Sound engineer, mixer, mastering support',
        ],
        addOns: [
          'Additional microphone (+2,000)',
          'Vocal booth rental (+3,000)',
        ],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete band recording setup with full production support.',
        price: '25,000',
        features: [
          'Full band recording capability',
          'Advanced mixing and mastering',
          'Professional production support',
          'Complete studio setup',
          'Expert production team',
        ],
        equipment: [
          'Recording: 24-channel multi-track interface',
          'Mixing: Professional mixing console (Allen & Heath)',
          'Microphone: 12× Professional studio microphones',
          'Drums: Complete drum recording setup',
          'Acoustic: Full professional acoustic treatment',
          'Monitoring: Complete professional monitoring',
          'Mastering: Mastering-grade tools',
          'Others: All cables, connectors, extensions',
          'Crew: Sound engineer, mixer, mastering engineer',
        ],
        sampleImages: [
          '/event-types/multi-track-studio-recording/studio-recording-1.jpg',
        ],
        addOns: [
          '2× Additional microphones (+2,000)',
          'Vocal booth rental (+3,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium recording with complete production and video support.',
        price: '30,000',
        features: [
          'Concert-level recording quality',
          'Full band production',
          'Advanced video support',
          'Mastering included',
          'Top production team',
        ],
        equipment: [
          'Recording: 24-channel multi-track interface + backup',
          'Mixing: Professional mixing console with outboard gear',
          'Microphone: 16× Professional studio microphones',
          'Drums: Professional drum recording setup',
          'Acoustic: Premium professional acoustic treatment',
          'Monitoring: Concert-grade monitoring system',
          'Mastering: Full mastering capability',
          'Video: Recording and monitoring capabilities',
          'Others: All professional cables, connectors, extensions',
          'Crew: Sound engineer, mixer, mastering engineer, producer',
        ],
        sampleImages: [
          '/event-types/multi-track-studio-recording/studio-recording-1.jpg',
        ],
        addOns: [
          '2× Additional microphones (+2,000)',
          'Video recording support (+3,000)',
        ],
      },
    ],
  },
  {
    category: 'backline-rental',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description: 'Essential instrument amplifier rental for performances.',
        price: '7,000',
        features: [
          'Quality amplifiers',
          'Basic equipment setup',
          'Suitable for rehearsals',
          'Transport included',
          'Professional setup',
        ],
        equipment: [
          'Amplifiers: 1× Guitar amp (50W)',
          'Amplifiers: 1× Bass amp (50W)',
          'Amplifiers: 1× Keyboard amp',
          'Others: Cables, stands, connectors',
          'Setup: Basic equipment setup service',
          'Transport: Transport service',
        ],
        sampleImages: ['/event-types/backline-rental/backline-rental-1.jpg'],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description: 'Enhanced amplifier setup with additional equipment.',
        price: '10,000',
        features: [
          'Improved amplification',
          'Better sound coverage',
          'Multiple instrument support',
          'Professional setup',
          'Expert technician',
        ],
        equipment: [
          'Amplifiers: 1× Guitar amp (100W)',
          'Amplifiers: 1× Bass amp (100W)',
          'Amplifiers: 1× Keyboard amp (150W)',
          'Others: Cables, stands, effect processors',
          'Setup: Professional equipment setup',
          'Transport: Transport service',
        ],
        addOns: [
          'Additional guitar amp (+2,500)',
          'Bass cabinet upgrade (+3,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Premium backline with monitoring and full support.',
        price: '12,000',
        features: [
          'Premium amplifiers',
          'Full instrument coverage',
          'Monitor support',
          'Professional equipment',
          'Expert support',
        ],
        equipment: [
          'Amplifiers: 2× Guitar amps (120W each)',
          'Amplifiers: 1× Bass amp (100W)',
          'Amplifiers: 1× Keyboard amp (150W)',
          'Monitoring: Monitor speaker setup',
          'Others: All cables, stands, processors',
          'Setup: Complete setup and testing',
          'Transport: Transport service',
        ],
        addOns: [
          'Additional guitar amp (+2,500)',
          'Bass cabinet upgrade (+3,000)',
        ],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description: 'Advanced backline setup with complete technical support.',
        price: '15,000',
        features: [
          'High-end amplifiers',
          'Full band amplification',
          'Complete technical support',
          'Professional-grade equipment',
          'Expert crew',
        ],
        equipment: [
          'Amplifiers: 2× Guitar amps (150W each)',
          'Amplifiers: 1× Bass amp (150W)',
          'Amplifiers: 1× Keyboard amp (200W)',
          'Amplifiers: 1× Drum amp (100W)',
          'Monitoring: Complete monitoring system',
          'Others: Premium cables, stands, processors',
          'Setup: Complete setup and testing',
          'Transport: Transport service',
        ],
        addOns: [
          'Additional guitar amp (+2,500)',
          'Bass cabinet upgrade (+3,000)',
        ],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description: 'Complete band backline with all instruments supported.',
        price: '25,000',
        features: [
          'Full band amplification',
          'All instruments covered',
          'Complete monitoring',
          'Professional-grade equipment',
          'Expert technical team',
        ],
        equipment: [
          'Amplifiers: 3× Guitar amps (150W each)',
          'Amplifiers: 1× Bass amp (200W)',
          'Amplifiers: 1× Keyboard amp (200W)',
          'Amplifiers: Complete drum amp setup',
          'Monitoring: Multi-channel monitoring',
          'Others: Premium cables, effects, stands',
          'Setup: Complete professional setup',
          'Transport: Full transport service',
        ],
        sampleImages: ['/event-types/backline-rental/backline-rental-1.jpg'],
        addOns: [
          '2× Additional guitar amps (+2,500)',
          'Bass cabinet upgrade (+3,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium band backline with lighting and complete production.',
        price: '30,000',
        features: [
          'Concert-level backline',
          'Complete band setup',
          'Integrated lighting',
          'Full production support',
          'Premium technical team',
        ],
        equipment: [
          'Amplifiers: 4× Guitar amps (200W each)',
          'Amplifiers: 1× Bass amp (250W)',
          'Amplifiers: 1× Keyboard amp (250W)',
          'Amplifiers: Professional drum amp setup',
          'Monitoring: Full multi-channel monitoring',
          'Lights: Stage lighting integration',
          'Others: Premium cables, effects, stands',
          'Setup: Complete professional setup',
          'Transport: Full transport service',
        ],
        sampleImages: ['/event-types/backline-rental/backline-rental-1.jpg'],
        addOns: [
          '2× Additional guitar amps (+2,500)',
          'Bass cabinet upgrade (+3,000)',
        ],
      },
    ],
  },
  {
    category: 'simple-wedding-setup',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description:
          'Simple yet elegant audio for intimate wedding ceremonies.',
        price: '7,000',
        features: [
          'Clear audio for vows',
          'Romantic ambient lighting',
          'Elegant setup',
          'Ceremony support',
          'Professional technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer',
          'Microphone: 2× Wireless microphones (for vows)',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stand',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/simple-wedding-setup/wedding-setup-1.jpg'],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description: 'Enhanced wedding setup with subwoofers for better audio.',
        price: '10,000',
        features: [
          'Better sound quality',
          'Enhanced ambient lighting',
          'Ceremony and reception support',
          'Professional setup',
          'Experienced technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 1× Mixer',
          'Microphone: 2× Wireless microphones (for vows)',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stand',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Premium wedding setup with full audio support.',
        price: '12,000',
        features: [
          'Premium audio quality',
          'Elegant lighting design',
          'Full ceremony support',
          'Professional lighting',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless microphones',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stand',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description:
          'Advanced wedding setup with enhanced lighting for special moments.',
        price: '15,000',
        features: [
          'Excellent audio quality',
          'Sophisticated lighting design',
          'Full event support',
          'Professional lighting effects',
          'Expert technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless microphones',
          'Lights: 8× PAR backlights, 8× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stand',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description: 'Complete wedding setup with live band and full support.',
        price: '25,000',
        features: [
          'Full band audio support',
          'Dynamic wedding lighting',
          'Professional monitoring',
          'Complete ceremony and reception setup',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Optional drumset with miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 4× T-bars',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/simple-wedding-setup/wedding-setup-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description:
          'Premium wedding package with moving lights for unforgettable moments.',
        price: '30,000',
        features: [
          'Concert-level band audio',
          'Full band with all equipment',
          'Moving lights for impact',
          'Premium presentation',
          'Top technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 2× Moving headlights',
          'Lights: 2× Moving wash, 4× T-bars, 1× Controller',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/simple-wedding-setup/wedding-setup-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'simple-corporate-setup',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description: 'Simple professional audio for corporate meetings.',
        price: '7,000',
        features: [
          'Clear presentation audio',
          'Professional appearance',
          'Basic lighting setup',
          'Meeting-appropriate design',
          'Experienced technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer',
          'Microphone: 2× Wireless microphones, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/simple-corporate-setup/corporate-setup-1.jpg',
        ],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description: 'Enhanced corporate setup with better audio projection.',
        price: '10,000',
        features: [
          'Improved sound quality',
          'Better coverage',
          'Professional image',
          'Enhanced presentation',
          'Experienced crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Professional corporate setup with monitoring.',
        price: '12,000',
        features: [
          'Professional-grade audio',
          'Enhanced presentation support',
          'Better stage presence',
          'Professional lighting',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description:
          'Advanced corporate setup with enhanced presentation features.',
        price: '15,000',
        features: [
          'High-quality presentation audio',
          'Professional lighting design',
          'Large venue support',
          'Advanced features',
          'Expert team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphones',
          'Lights: 8× PAR backlights, 8× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description:
          'Complete entertainment setup for premium corporate events.',
        price: '25,000',
        features: [
          'Full band audio support',
          'Dynamic stage lighting',
          'Professional monitoring',
          'Complete event support',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 4× T-bars',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/simple-corporate-setup/corporate-setup-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description: 'Premium package with moving lights for maximum impact.',
        price: '30,000',
        features: [
          'Concert-level setup',
          'Full band with equipment',
          'Dynamic moving lights',
          'Large venue capability',
          'Premium technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 2× Moving headlights',
          'Lights: 2× Moving wash, 4× T-bars, 1× Controller',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/simple-corporate-setup/corporate-setup-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'food-park-setup',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description: 'Entertainment sound for outdoor food park events.',
        price: '7,000',
        features: [
          'Lively outdoor sound',
          'Festive lighting',
          'Wide coverage',
          'Entertainment focus',
          'Professional technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/food-park-setup/food-park-setup-1.jpg'],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description: 'Enhanced outdoor setup with subwoofers.',
        price: '10,000',
        features: [
          'High-power outdoor sound',
          'Festive lighting',
          'Large space coverage',
          'Entertainment support',
          'Professional crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Professional outdoor entertainment setup.',
        price: '12,000',
        features: [
          'Professional outdoor audio',
          'Festive atmosphere',
          'Wide coverage',
          'Entertainment support',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description: 'Advanced outdoor setup with enhanced lighting.',
        price: '15,000',
        features: [
          'High-power outdoor sound',
          'Dynamic lighting design',
          'Large venue support',
          'Entertainment setup',
          'Expert team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 8× PAR backlights, 8× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description: 'Complete entertainment for large food park events.',
        price: '25,000',
        features: [
          'Full band audio support',
          'Dynamic outdoor lighting',
          'Professional monitoring',
          'Large crowd entertainment',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 4× T-bars',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/food-park-setup/food-park-setup-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description: 'Premium outdoor setup with moving lights.',
        price: '30,000',
        features: [
          'Concert-level outdoor system',
          'Full band with equipment',
          'Dynamic moving lights',
          'Maximum visual impact',
          'Top technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 2× Moving headlights',
          'Lights: 2× Moving wash, 4× T-bars, 1× Controller',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: ['/event-types/food-park-setup/food-park-setup-1.jpg'],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
  {
    category: 'barangay-gymnasium-events',
    packages: [
      {
        id: 1,
        name: 'Basic Sounds and Lights Package',
        description: 'Community-friendly audio for barangay events.',
        price: '7,000',
        features: [
          'Clear community sound',
          'Gymnasium coverage',
          'Colorful lighting',
          'Event support',
          'Professional technician',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 2× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/barangay-gymnasium-events/barangay-gym-events-1.jpg',
        ],
      },
      {
        id: 2,
        name: 'Sounds and Lights with Subwoofers Package',
        description: 'Enhanced setup for larger barangay gatherings.',
        price: '10,000',
        features: [
          'Better sound coverage',
          'Professional quality',
          'Gymnasium reach',
          'Community support',
          'Experienced crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: [
          '2× Monitor speakers (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 3,
        name: 'Sounds and Lights with Sub and Monitors Package',
        description: 'Professional setup for community gymnasium events.',
        price: '12,000',
        features: [
          'Professional-grade sound',
          'Full gymnasium coverage',
          'Stage monitoring',
          'Community presentation',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 4× PAR backlights, 4× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 4,
        name: 'Sounds and Lights with Sub and Monitors Plus Package',
        description: 'Advanced setup with enhanced lighting for major events.',
        price: '15,000',
        features: [
          'Professional sound system',
          'Enhanced lighting',
          'Large event support',
          'Community presentation',
          'Expert team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 2× Monitors, 1× Mixer',
          'Microphone: 2× Wireless, 1× Wired microphone',
          'Lights: 8× PAR backlights, 8× Amber lights, 1× DMX Controller',
          'Others: 2× Speaker stands, cables, extensions, mic stands',
          'Crew & Transport: 3× Tech crew, transport service',
        ],
        addOns: ['2× Moving headlights (+2,000)'],
      },
      {
        id: 5,
        name: 'Sounds and Lights with Full Band Setup Package',
        description: 'Complete entertainment for major barangay celebrations.',
        price: '25,000',
        features: [
          'Full band audio support',
          'Dynamic stage lighting',
          'Professional monitoring',
          'Community entertainment',
          'Expert crew',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 4× T-bars',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/barangay-gymnasium-events/barangay-gym-events-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
      {
        id: 6,
        name: 'Sounds and Lights with Full Band and Moving Lights Package',
        description: 'Premium setup with moving lights for grand celebrations.',
        price: '30,000',
        features: [
          'Concert-level system',
          'Full band with equipment',
          'Dynamic moving lights',
          'Grand celebration support',
          'Top technical team',
        ],
        equipment: [
          'Audio System: 2× Powered speakers, 2× Subwoofers, 4× Monitors',
          'Audio System: 1× Digital mixer, 1× Digital stage box',
          'Microphone: 2× Wireless, 2× Wired microphones',
          'Drums: Complete drumset with professional miking',
          'Amplifiers: 2× Guitar amps, 1× Bass amp',
          'Lights: 8× PAR backlights, 4× Amber lights, 2× Moving headlights',
          'Lights: 2× Moving wash, 4× T-bars, 1× Controller',
          'Others: Speaker stands, cables, extensions, mic stands, fog machine',
          'Crew & Transport: 5× Tech crew, transport service',
        ],
        sampleImages: [
          '/event-types/barangay-gymnasium-events/barangay-gym-events-1.jpg',
        ],
        addOns: [
          '2× Yamaha monitors (+2,000)',
          '2× Moving headlights (+2,000)',
        ],
      },
    ],
  },
]
